/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; fill-column: 100 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

module com { module sun { module star { module script { module browse {

/**
   An optional interface that can be added to implementations of XBrowseNode in order to make the
   node copyable.

   Since LibreOffice 27.2
*/
interface XCopyableBrowseNode
{
    /**
     * @returns whether this node can be used as the source for a copy operation.
     */
    boolean isCopyableNode();

    /**
     * @returns whether this node can be copied to be a child of the destination node.
     *
     * @param parentNode - The parent to copy this node to.
     */
    boolean nodeCanBeCopiedTo([in] XBrowseNode parentNode);

    /**
     * Copy the node.
     */
    XBrowseNode copyNode([in] XBrowseNode parentNode)
        raises(com::sun::star::uno::Exception);
};

}; }; }; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab cinoptions=b1,g0,N-s cinkeys+=0=break: */
